repos:
# As per BCR itself
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
  - id: ruff
  - id: ruff-format
# Buildifier is great.
- repo: https://github.com/warchant/pre-commit-buildifier
  rev: f8ce12ccaf29ba79d19c6a9d0643471372a8ba0f
  hooks:
    - id: buildifier
