repos:
# As per BCR itself
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
  - id: ruff-format
# Buildifier is great.
- repo: https://github.com/warchant/pre-commit-buildifier
  rev: f8ce12ccaf29ba79d19c6a9d0643471372a8ba0f
  hooks:
    - id: buildifier
# clang-format for C/C++ files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.3
  hooks:
    - id: clang-format
      types_or: [c, c++]
